sudo: required
services:
  - docker

before_install:
  - docker build -t igorz/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run igorz/react-test npm test -- --coverage

after_success:
  - docker build -t igorz/multi-client ./client
  - docker build -t igorz/multi-nginx ./nginx
  - docker build -t igorz/multi-server ./server
  - docker build -t igorz/multi-worker ./worker
  
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  - docker push igorz/multi-client
  - docker push igorz/multi-nginx
  - docker push igorz/multi-server
  - docker push igorz/multi-worker
